
version: '3.3'

networks:
  app-network:
    driver: bridge

services:
    mysql-database:
        container_name: mysql-database
        restart: always
        image: mysql-database:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - "./service-mysql/config/my.conf:/etc/mysql/conf.d/config-file.cnf"
            - "./service-mysql/data:/var/lib/mysql:rw"
        ports:
            - "3306:3306"
        networks:
            - app-network

    web-app:
        container_name: web-app
        image: web-app:latest
        ports:
            - "8000:8000"
        networks:
            - app-network
        depends_on:
            - "mysql-database"

    scraper-cache:
        container_name: scraper-cache
        image: scraper-cache:latest
        networks:
            - app-network
        depends_on:
            - "mysql-database"
            - "web-app"
