version: '3.3'
services:

    mysql:
        container_name: res-database
        restart: always
        image: res-database:latest
        environment: 
            MYSQL_ROOT_PASSWORD: 'toor'
            MYSQL_USER: 'resdb'
            MYSQL_PASS: 'password'
        volumes:
            - "./res-database/config/my.conf:/etc/mysql/conf.d/config-file.cnf"
            - "./res-database/data:/var/lib/mysql:rw"
        ports:
            - "3306:3306"

    webapp:
        container_name: web-app
        image: web-app:latest
        ports:
            - "5000:5000"
        depends_on:
            - "mysql"
