FROM python:latest

RUN pip install pandas
RUN pip install beautifulsoup4
RUN pip install mysql-connector-python
RUN pip install requests

CMD ["python3", "ScraperCache.py"]

COPY config.json /config.json
COPY src/* /
COPY service-scache/ScraperCache.py ScraperCache.py