FROM python:latest
EXPOSE 5000
RUN pip install flask
RUN pip install mysql-connector-python
RUN pip install pandas
CMD ["python3", "webapp.py"]
COPY templates /templates
COPY DatabaseConnection.py /DatabaseConnection.py
COPY webapp.py /webapp.py
COPY config.json /config.json
