FROM python:latest
RUN pip install beautifulsoup4
RUN pip install pandas
RUN pip install requests
RUN pip install mysql-connector-python
CMD ["python3", "ScraperApp.py"]
COPY Scraper.py /Scraper.py
COPY GoogleScraper.py /GoogleScraper.py 
COPY ScraperApp.py /ScraperApp.py
COPY config.json /config.json
